name: pdf_creation_flutter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pdf: ^3.10.1
  path_provider: ^2.0.15
  printing: ^5.10.4
  permission_handler: ^10.2.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: open_sans
      fonts:
        - asset: assets/fonts/open_sans.ttf